baseurl = "https://www.jmordonez.com/"
title = "Jose Ordoñez"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "joseordonez"

[params]
    author = "Jose M. Ordoñez"
    description = "Jose Ordoñez's personal website"
    keywords = "blog,developer,personal,devops,cloud,software"
    info = "Software Engineer - Agile, Cloud and DevOps Enthusiast"
    avatarurl = "/images/Me.jpg"
    footercontent = "DevOps and Cloud rules!"

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = true

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/josema88/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/josemaord/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/jose-manuel-ordonez-castillo/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 4
    url = "https://www.instagram.com/josemaord/"    


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Videos"
            weight = 3
            url = "videos/"
            
            [[languages.en.menu.main]]
            name = "Events"
            weight = 4
            url = "events/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 5
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 6
            url = "contact/"
