---
label: posts template
hide_body: false
fields:
- type: list
  name: categories
  label: categories
- type: datetime
  name: date
  label: date
- type: list
  name: series
  label: series
- type: text
  name: slug
  label: slug
- type: list
  name: tags
  label: tags
- type: text
  name: title
  label: title
- name: image
  type: file
  config:
    maxSize: 64
  label: image
pages:
- content/events/manizales-tech-talks-1.md
- content/events/shipping-my-asp-net-core-app-to-azure.md
- content/events/tech-community-day-2020.md
- content/posts/why-should-you-consider-rest-apis-for-your-application-architecture.md
