---
label: Why should you consider REST APIs for your application architecture?
hide_body: false
fields:
- type: list
  name: categories
  label: categories
- type: datetime
  name: date
  label: date
- type: list
  name: series
  label: series
- type: text
  name: slug
  label: slug
- type: list
  name: tags
  label: tags
- type: text
  name: title
  label: title
pages:
- content/posts/why-should-you-consider-rest-apis-for-your-application-architecture.md
